### ISSUE TITLE
Plugin it not loaded on non opencl machine

### ISSUE THREAD

**Issue by Ichunjo** [HomeOfVapourSynthEvolution/VapourSynth-EEDI3#3]
Hello, as the title says I'm trying to install the plugin on my Windows Server 2019 which has a Ryzen 3600.

AMD CPU doesn't have opencl support as far as I know so I tried to compile with `-Dopencl=false` setting but it doesn't work either.
(it was with msys2 btw)

Is it possible to have a compiled dll for windows without any opencl support on it, please?
I don't think I would be the only one with same trouble since AMD CPUs are now better than Intel for encoding.

Thanks in advance.

**Comment by HolyWu** [comment]
Please try https://github.com/HomeOfVapourSynthEvolution/VapourSynth-EEDI3/releases/download/r4/EEDI3-r4_non-OpenCL.7z.

**Comment by Ichunjo** [comment]
Oh my god it works...

I am very grateful to you. Very thanks! What did you do? Just a regular compilation with `-Dopencl=false`?

**Comment by HolyWu** [comment]
I used Visual Studio for compilation. But specifying `-Dopencl=false` in meson should also do the job.
